#!/bin/bash -ex

RAILS_DIR=/var/www/railsapp

# generate controller
cd $RAILS_DIR
ruby script/generate controller --skip cp

# configure routing
sed -i "s|^end|  map.root :controller => \"cp\"\nend|" $RAILS_DIR/config/routes.rb

# configure tkl-webcp
cp -a /var/www/js/* $RAILS_DIR/public/javascripts
cp -a /var/www/css/* $RAILS_DIR/public/stylesheets
cp -a /var/www/images/* $RAILS_DIR/public/images
rm -rf /var/www/{js,css,images}

# remove default index
rm -f $RAILS_DIR/public/index.html
