#!/bin/bash -ex
WEBROOT=/var/www/railsapp
LOGDIR=/var/log/railsapp

# update gemfile
cat >> $WEBROOT/Gemfile<<EOF
gem 'execjs'
EOF

# install bundle and generate controller
service mysql start
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
cd $WEBROOT

bundle install
rails generate controller cp # touches development.log
chown -R www-data:www-data $LOGDIR
chown -R www-data:www-data $WEBROOT/log
chown -R www-data:www-data $WEBROOT/tmp/cache
chmod g+r $WEBROOT/config/master.key
unset HTTP_PROXY
service mysql stop

# apply railsapp webcp overlay
cp -TdR $WEBROOT.overlay $WEBROOT
rm -rf $WEBROOT.overlay

# configure tkl-webcp

mkdir $WEBROOT/app/javascript/images
cp -a /var/www/js/ui* $WEBROOT/app/javascript/packs/
cp -a /var/www/css/* $WEBROOT/app/javascript/stylesheets/
cp -a /var/www/images/* $WEBROOT/app/javascript/images/

# Webpacker breaks with dot in filename, rename webcp files to use hyphen
cd $WEBROOT/app/javascript/stylesheets

mv base.css base.scss
# remove the line containing loading.gif for absence of the file and rename to scss.
grep -v "loading.gif" ui.tabs.css > ui-tabs.scss

cd $WEBROOT/app/javascript/packs

mv ui.tabs.js ui-tabs.js
mv ui.core.js ui-core.js

rm -rf /var/www/{js,css,images}


# remove default index
rm -f $WEBROOT/public/index.html

