#!/bin/bash -e

. /etc/default/inithooks

export RAILS_ENV=production

webroot=/var/www/railsapp
credentials=$webroot/config/credentials.yml.enc
master_key=$webroot/config/master.key
stamp=$(date +%s)

echo "Regenerating Rails credentials"
for file in "$credentials" "$master_key"; do
    if [[ -f $file ]]; then
        backup="$file.$stamp.bak"
        echo "Backing up $file as $backup" >&2
        mv "$file" "$backup"
    fi
done

cd "$webroot"
EDITOR=echo /usr/bin/rails credentials:edit
chown root:www-data "$credentials" "$master_key"
chmod 0640 "$credentials" "$master_key"

password=$(mcookie)
sed -i "s/^\([[:space:]]*password:\).*/\1 \"$password\"/" \
    "$webroot/config/database.yml"
"$INITHOOKS_PATH/bin/mysqlconf.py" --user=railsapp --pass="$password"

touch "$webroot/tmp/restart.txt"
