SetEnv RAILS_ENV production
PassengerAppEnv production

DocumentRoot /var/www/railsapp/public/

<Directory /var/www/railsapp/public/>
    Options +FollowSymLinks -MultiViews
    AllowOverride all
    Require all granted
</Directory>
