ServerName localhost

<VirtualHost *:80>
    UseCanonicalName Off
    Include /etc/apache2/conf-available/railsapp.conf
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    RequestHeader set X_FORWARDED_PROTO "https"
    Include /etc/apache2/conf-available/railsapp.conf
</VirtualHost>
